# Site settings
title: Contact Query App
email: your-email@domain.com
description: "Fast, simple, responsive contact finder."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: null
